# Generated by Django 4.0 on 2021-12-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
                ('mobile', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
